//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frontjava.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices/", ConfigurationName="ServiceReference1.Servicios")]
    public interface Servicios {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/agregarPersonaRequest", ReplyAction="http://WebServices/Servicios/agregarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.agregarPersonaResponse agregarPersona(frontjava.ServiceReference1.agregarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/agregarPersonaRequest", ReplyAction="http://WebServices/Servicios/agregarPersonaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarPersonaResponse> agregarPersonaAsync(frontjava.ServiceReference1.agregarPersonaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/tarjetaIdRequest", ReplyAction="http://WebServices/Servicios/tarjetaIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.tarjetaIdResponse tarjetaId(frontjava.ServiceReference1.tarjetaIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/tarjetaIdRequest", ReplyAction="http://WebServices/Servicios/tarjetaIdResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.tarjetaIdResponse> tarjetaIdAsync(frontjava.ServiceReference1.tarjetaIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/editarTarjetaRequest", ReplyAction="http://WebServices/Servicios/editarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.editarTarjetaResponse editarTarjeta(frontjava.ServiceReference1.editarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/editarTarjetaRequest", ReplyAction="http://WebServices/Servicios/editarTarjetaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.editarTarjetaResponse> editarTarjetaAsync(frontjava.ServiceReference1.editarTarjetaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/editarPersonaRequest", ReplyAction="http://WebServices/Servicios/editarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.editarPersonaResponse editarPersona(frontjava.ServiceReference1.editarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/editarPersonaRequest", ReplyAction="http://WebServices/Servicios/editarPersonaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.editarPersonaResponse> editarPersonaAsync(frontjava.ServiceReference1.editarPersonaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarTarjetasRequest", ReplyAction="http://WebServices/Servicios/listarTarjetasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.listarTarjetasResponse listarTarjetas(frontjava.ServiceReference1.listarTarjetasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarTarjetasRequest", ReplyAction="http://WebServices/Servicios/listarTarjetasResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasResponse> listarTarjetasAsync(frontjava.ServiceReference1.listarTarjetasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/eliminarTarjetaRequest", ReplyAction="http://WebServices/Servicios/eliminarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.eliminarTarjetaResponse eliminarTarjeta(frontjava.ServiceReference1.eliminarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/eliminarTarjetaRequest", ReplyAction="http://WebServices/Servicios/eliminarTarjetaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarTarjetaResponse> eliminarTarjetaAsync(frontjava.ServiceReference1.eliminarTarjetaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarPersonaRequest", ReplyAction="http://WebServices/Servicios/listarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.listarPersonaResponse listarPersona(frontjava.ServiceReference1.listarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarPersonaRequest", ReplyAction="http://WebServices/Servicios/listarPersonaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarPersonaResponse> listarPersonaAsync(frontjava.ServiceReference1.listarPersonaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/agregarTarjetaRequest", ReplyAction="http://WebServices/Servicios/agregarTarjetaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.agregarTarjetaResponse agregarTarjeta(frontjava.ServiceReference1.agregarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/agregarTarjetaRequest", ReplyAction="http://WebServices/Servicios/agregarTarjetaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarTarjetaResponse> agregarTarjetaAsync(frontjava.ServiceReference1.agregarTarjetaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/personaIdRequest", ReplyAction="http://WebServices/Servicios/personaIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.personaIdResponse personaId(frontjava.ServiceReference1.personaIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/personaIdRequest", ReplyAction="http://WebServices/Servicios/personaIdResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.personaIdResponse> personaIdAsync(frontjava.ServiceReference1.personaIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/eliminarPersonaRequest", ReplyAction="http://WebServices/Servicios/eliminarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.eliminarPersonaResponse eliminarPersona(frontjava.ServiceReference1.eliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/eliminarPersonaRequest", ReplyAction="http://WebServices/Servicios/eliminarPersonaResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarPersonaResponse> eliminarPersonaAsync(frontjava.ServiceReference1.eliminarPersonaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarTarjetasLibresRequest", ReplyAction="http://WebServices/Servicios/listarTarjetasLibresResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        frontjava.ServiceReference1.listarTarjetasLibresResponse listarTarjetasLibres(frontjava.ServiceReference1.listarTarjetasLibresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/Servicios/listarTarjetasLibresRequest", ReplyAction="http://WebServices/Servicios/listarTarjetasLibresResponse")]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasLibresResponse> listarTarjetasLibresAsync(frontjava.ServiceReference1.listarTarjetasLibresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPersona", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class agregarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTarjeta;
        
        public agregarPersonaRequest() {
        }
        
        public agregarPersonaRequest(string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.telefono = telefono;
            this.direccion = direccion;
            this.correo = correo;
            this.idTarjeta = idTarjeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarPersonaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class agregarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public agregarPersonaResponse() {
        }
        
        public agregarPersonaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServices/")]
    public partial class tarjeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int agnoField;
        
        private int codigoField;
        
        private int idField;
        
        private int mesField;
        
        private string numeroField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int agno {
            get {
                return this.agnoField;
            }
            set {
                this.agnoField = value;
                this.RaisePropertyChanged("agno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
                this.RaisePropertyChanged("mes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServices/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string correoField;
        
        private string direccionField;
        
        private int idField;
        
        private int idTarjetaField;
        
        private string nombreField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idTarjeta {
            get {
                return this.idTarjetaField;
            }
            set {
                this.idTarjetaField = value;
                this.RaisePropertyChanged("idTarjeta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tarjetaId", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class tarjetaIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public tarjetaIdRequest() {
        }
        
        public tarjetaIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tarjetaIdResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class tarjetaIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frontjava.ServiceReference1.tarjeta @return;
        
        public tarjetaIdResponse() {
        }
        
        public tarjetaIdResponse(frontjava.ServiceReference1.tarjeta @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarTarjeta", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class editarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int agno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigo;
        
        public editarTarjetaRequest() {
        }
        
        public editarTarjetaRequest(int id, string nombres, int agno, int mes, int codigo) {
            this.id = id;
            this.nombres = nombres;
            this.agno = agno;
            this.mes = mes;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarTarjetaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class editarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public editarTarjetaResponse() {
        }
        
        public editarTarjetaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarPersona", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class editarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTarjeta;
        
        public editarPersonaRequest() {
        }
        
        public editarPersonaRequest(int id, string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            this.id = id;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.telefono = telefono;
            this.direccion = direccion;
            this.correo = correo;
            this.idTarjeta = idTarjeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editarPersonaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class editarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public editarPersonaResponse() {
        }
        
        public editarPersonaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTarjetas", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarTarjetasRequest {
        
        public listarTarjetasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTarjetasResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarTarjetasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frontjava.ServiceReference1.tarjeta[] @return;
        
        public listarTarjetasResponse() {
        }
        
        public listarTarjetasResponse(frontjava.ServiceReference1.tarjeta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTarjeta", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class eliminarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarTarjetaRequest() {
        }
        
        public eliminarTarjetaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTarjetaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class eliminarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public eliminarTarjetaResponse() {
        }
        
        public eliminarTarjetaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersona", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarPersonaRequest {
        
        public listarPersonaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frontjava.ServiceReference1.persona[] @return;
        
        public listarPersonaResponse() {
        }
        
        public listarPersonaResponse(frontjava.ServiceReference1.persona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarTarjeta", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class agregarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int agno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigo;
        
        public agregarTarjetaRequest() {
        }
        
        public agregarTarjetaRequest(string nombres, int agno, int mes, int codigo) {
            this.nombres = nombres;
            this.agno = agno;
            this.mes = mes;
            this.codigo = codigo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarTarjetaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class agregarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public agregarTarjetaResponse() {
        }
        
        public agregarTarjetaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="personaId", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class personaIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public personaIdRequest() {
        }
        
        public personaIdRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="personaIdResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class personaIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frontjava.ServiceReference1.persona @return;
        
        public personaIdResponse() {
        }
        
        public personaIdResponse(frontjava.ServiceReference1.persona @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersona", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonaResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTarjetasLibres", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarTarjetasLibresRequest {
        
        public listarTarjetasLibresRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTarjetasLibresResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class listarTarjetasLibresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public frontjava.ServiceReference1.tarjeta[] @return;
        
        public listarTarjetasLibresResponse() {
        }
        
        public listarTarjetasLibresResponse(frontjava.ServiceReference1.tarjeta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosChannel : frontjava.ServiceReference1.Servicios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosClient : System.ServiceModel.ClientBase<frontjava.ServiceReference1.Servicios>, frontjava.ServiceReference1.Servicios {
        
        public ServiciosClient() {
        }
        
        public ServiciosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.agregarPersonaResponse frontjava.ServiceReference1.Servicios.agregarPersona(frontjava.ServiceReference1.agregarPersonaRequest request) {
            return base.Channel.agregarPersona(request);
        }
        
        public string agregarPersona(string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            frontjava.ServiceReference1.agregarPersonaRequest inValue = new frontjava.ServiceReference1.agregarPersonaRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.telefono = telefono;
            inValue.direccion = direccion;
            inValue.correo = correo;
            inValue.idTarjeta = idTarjeta;
            frontjava.ServiceReference1.agregarPersonaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).agregarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarPersonaResponse> frontjava.ServiceReference1.Servicios.agregarPersonaAsync(frontjava.ServiceReference1.agregarPersonaRequest request) {
            return base.Channel.agregarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarPersonaResponse> agregarPersonaAsync(string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            frontjava.ServiceReference1.agregarPersonaRequest inValue = new frontjava.ServiceReference1.agregarPersonaRequest();
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.telefono = telefono;
            inValue.direccion = direccion;
            inValue.correo = correo;
            inValue.idTarjeta = idTarjeta;
            return ((frontjava.ServiceReference1.Servicios)(this)).agregarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.tarjetaIdResponse frontjava.ServiceReference1.Servicios.tarjetaId(frontjava.ServiceReference1.tarjetaIdRequest request) {
            return base.Channel.tarjetaId(request);
        }
        
        public frontjava.ServiceReference1.tarjeta tarjetaId(int id) {
            frontjava.ServiceReference1.tarjetaIdRequest inValue = new frontjava.ServiceReference1.tarjetaIdRequest();
            inValue.id = id;
            frontjava.ServiceReference1.tarjetaIdResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).tarjetaId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.tarjetaIdResponse> frontjava.ServiceReference1.Servicios.tarjetaIdAsync(frontjava.ServiceReference1.tarjetaIdRequest request) {
            return base.Channel.tarjetaIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.tarjetaIdResponse> tarjetaIdAsync(int id) {
            frontjava.ServiceReference1.tarjetaIdRequest inValue = new frontjava.ServiceReference1.tarjetaIdRequest();
            inValue.id = id;
            return ((frontjava.ServiceReference1.Servicios)(this)).tarjetaIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.editarTarjetaResponse frontjava.ServiceReference1.Servicios.editarTarjeta(frontjava.ServiceReference1.editarTarjetaRequest request) {
            return base.Channel.editarTarjeta(request);
        }
        
        public string editarTarjeta(int id, string nombres, int agno, int mes, int codigo) {
            frontjava.ServiceReference1.editarTarjetaRequest inValue = new frontjava.ServiceReference1.editarTarjetaRequest();
            inValue.id = id;
            inValue.nombres = nombres;
            inValue.agno = agno;
            inValue.mes = mes;
            inValue.codigo = codigo;
            frontjava.ServiceReference1.editarTarjetaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).editarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.editarTarjetaResponse> frontjava.ServiceReference1.Servicios.editarTarjetaAsync(frontjava.ServiceReference1.editarTarjetaRequest request) {
            return base.Channel.editarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.editarTarjetaResponse> editarTarjetaAsync(int id, string nombres, int agno, int mes, int codigo) {
            frontjava.ServiceReference1.editarTarjetaRequest inValue = new frontjava.ServiceReference1.editarTarjetaRequest();
            inValue.id = id;
            inValue.nombres = nombres;
            inValue.agno = agno;
            inValue.mes = mes;
            inValue.codigo = codigo;
            return ((frontjava.ServiceReference1.Servicios)(this)).editarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.editarPersonaResponse frontjava.ServiceReference1.Servicios.editarPersona(frontjava.ServiceReference1.editarPersonaRequest request) {
            return base.Channel.editarPersona(request);
        }
        
        public string editarPersona(int id, string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            frontjava.ServiceReference1.editarPersonaRequest inValue = new frontjava.ServiceReference1.editarPersonaRequest();
            inValue.id = id;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.telefono = telefono;
            inValue.direccion = direccion;
            inValue.correo = correo;
            inValue.idTarjeta = idTarjeta;
            frontjava.ServiceReference1.editarPersonaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).editarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.editarPersonaResponse> frontjava.ServiceReference1.Servicios.editarPersonaAsync(frontjava.ServiceReference1.editarPersonaRequest request) {
            return base.Channel.editarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.editarPersonaResponse> editarPersonaAsync(int id, string nombres, string apellidos, string telefono, string direccion, string correo, int idTarjeta) {
            frontjava.ServiceReference1.editarPersonaRequest inValue = new frontjava.ServiceReference1.editarPersonaRequest();
            inValue.id = id;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.telefono = telefono;
            inValue.direccion = direccion;
            inValue.correo = correo;
            inValue.idTarjeta = idTarjeta;
            return ((frontjava.ServiceReference1.Servicios)(this)).editarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.listarTarjetasResponse frontjava.ServiceReference1.Servicios.listarTarjetas(frontjava.ServiceReference1.listarTarjetasRequest request) {
            return base.Channel.listarTarjetas(request);
        }
        
        public frontjava.ServiceReference1.tarjeta[] listarTarjetas() {
            frontjava.ServiceReference1.listarTarjetasRequest inValue = new frontjava.ServiceReference1.listarTarjetasRequest();
            frontjava.ServiceReference1.listarTarjetasResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).listarTarjetas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasResponse> frontjava.ServiceReference1.Servicios.listarTarjetasAsync(frontjava.ServiceReference1.listarTarjetasRequest request) {
            return base.Channel.listarTarjetasAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasResponse> listarTarjetasAsync() {
            frontjava.ServiceReference1.listarTarjetasRequest inValue = new frontjava.ServiceReference1.listarTarjetasRequest();
            return ((frontjava.ServiceReference1.Servicios)(this)).listarTarjetasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.eliminarTarjetaResponse frontjava.ServiceReference1.Servicios.eliminarTarjeta(frontjava.ServiceReference1.eliminarTarjetaRequest request) {
            return base.Channel.eliminarTarjeta(request);
        }
        
        public string eliminarTarjeta(int id) {
            frontjava.ServiceReference1.eliminarTarjetaRequest inValue = new frontjava.ServiceReference1.eliminarTarjetaRequest();
            inValue.id = id;
            frontjava.ServiceReference1.eliminarTarjetaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).eliminarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarTarjetaResponse> frontjava.ServiceReference1.Servicios.eliminarTarjetaAsync(frontjava.ServiceReference1.eliminarTarjetaRequest request) {
            return base.Channel.eliminarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarTarjetaResponse> eliminarTarjetaAsync(int id) {
            frontjava.ServiceReference1.eliminarTarjetaRequest inValue = new frontjava.ServiceReference1.eliminarTarjetaRequest();
            inValue.id = id;
            return ((frontjava.ServiceReference1.Servicios)(this)).eliminarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.listarPersonaResponse frontjava.ServiceReference1.Servicios.listarPersona(frontjava.ServiceReference1.listarPersonaRequest request) {
            return base.Channel.listarPersona(request);
        }
        
        public frontjava.ServiceReference1.persona[] listarPersona() {
            frontjava.ServiceReference1.listarPersonaRequest inValue = new frontjava.ServiceReference1.listarPersonaRequest();
            frontjava.ServiceReference1.listarPersonaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).listarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarPersonaResponse> frontjava.ServiceReference1.Servicios.listarPersonaAsync(frontjava.ServiceReference1.listarPersonaRequest request) {
            return base.Channel.listarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.listarPersonaResponse> listarPersonaAsync() {
            frontjava.ServiceReference1.listarPersonaRequest inValue = new frontjava.ServiceReference1.listarPersonaRequest();
            return ((frontjava.ServiceReference1.Servicios)(this)).listarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.agregarTarjetaResponse frontjava.ServiceReference1.Servicios.agregarTarjeta(frontjava.ServiceReference1.agregarTarjetaRequest request) {
            return base.Channel.agregarTarjeta(request);
        }
        
        public string agregarTarjeta(string nombres, int agno, int mes, int codigo) {
            frontjava.ServiceReference1.agregarTarjetaRequest inValue = new frontjava.ServiceReference1.agregarTarjetaRequest();
            inValue.nombres = nombres;
            inValue.agno = agno;
            inValue.mes = mes;
            inValue.codigo = codigo;
            frontjava.ServiceReference1.agregarTarjetaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).agregarTarjeta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarTarjetaResponse> frontjava.ServiceReference1.Servicios.agregarTarjetaAsync(frontjava.ServiceReference1.agregarTarjetaRequest request) {
            return base.Channel.agregarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.agregarTarjetaResponse> agregarTarjetaAsync(string nombres, int agno, int mes, int codigo) {
            frontjava.ServiceReference1.agregarTarjetaRequest inValue = new frontjava.ServiceReference1.agregarTarjetaRequest();
            inValue.nombres = nombres;
            inValue.agno = agno;
            inValue.mes = mes;
            inValue.codigo = codigo;
            return ((frontjava.ServiceReference1.Servicios)(this)).agregarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.personaIdResponse frontjava.ServiceReference1.Servicios.personaId(frontjava.ServiceReference1.personaIdRequest request) {
            return base.Channel.personaId(request);
        }
        
        public frontjava.ServiceReference1.persona personaId(int id) {
            frontjava.ServiceReference1.personaIdRequest inValue = new frontjava.ServiceReference1.personaIdRequest();
            inValue.id = id;
            frontjava.ServiceReference1.personaIdResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).personaId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.personaIdResponse> frontjava.ServiceReference1.Servicios.personaIdAsync(frontjava.ServiceReference1.personaIdRequest request) {
            return base.Channel.personaIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.personaIdResponse> personaIdAsync(int id) {
            frontjava.ServiceReference1.personaIdRequest inValue = new frontjava.ServiceReference1.personaIdRequest();
            inValue.id = id;
            return ((frontjava.ServiceReference1.Servicios)(this)).personaIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.eliminarPersonaResponse frontjava.ServiceReference1.Servicios.eliminarPersona(frontjava.ServiceReference1.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public string eliminarPersona(int id) {
            frontjava.ServiceReference1.eliminarPersonaRequest inValue = new frontjava.ServiceReference1.eliminarPersonaRequest();
            inValue.id = id;
            frontjava.ServiceReference1.eliminarPersonaResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).eliminarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarPersonaResponse> frontjava.ServiceReference1.Servicios.eliminarPersonaAsync(frontjava.ServiceReference1.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.eliminarPersonaResponse> eliminarPersonaAsync(int id) {
            frontjava.ServiceReference1.eliminarPersonaRequest inValue = new frontjava.ServiceReference1.eliminarPersonaRequest();
            inValue.id = id;
            return ((frontjava.ServiceReference1.Servicios)(this)).eliminarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        frontjava.ServiceReference1.listarTarjetasLibresResponse frontjava.ServiceReference1.Servicios.listarTarjetasLibres(frontjava.ServiceReference1.listarTarjetasLibresRequest request) {
            return base.Channel.listarTarjetasLibres(request);
        }
        
        public frontjava.ServiceReference1.tarjeta[] listarTarjetasLibres() {
            frontjava.ServiceReference1.listarTarjetasLibresRequest inValue = new frontjava.ServiceReference1.listarTarjetasLibresRequest();
            frontjava.ServiceReference1.listarTarjetasLibresResponse retVal = ((frontjava.ServiceReference1.Servicios)(this)).listarTarjetasLibres(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasLibresResponse> frontjava.ServiceReference1.Servicios.listarTarjetasLibresAsync(frontjava.ServiceReference1.listarTarjetasLibresRequest request) {
            return base.Channel.listarTarjetasLibresAsync(request);
        }
        
        public System.Threading.Tasks.Task<frontjava.ServiceReference1.listarTarjetasLibresResponse> listarTarjetasLibresAsync() {
            frontjava.ServiceReference1.listarTarjetasLibresRequest inValue = new frontjava.ServiceReference1.listarTarjetasLibresRequest();
            return ((frontjava.ServiceReference1.Servicios)(this)).listarTarjetasLibresAsync(inValue);
        }
    }
}
